import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import dynamic from "next/dynamic";
import CrispWithNoSSR from "@/lib/Crisp";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footers/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CrispWithNoSSR />
      <body className={inter.className}>
        <Header />
        {children}
        <Toaster className="bg-white" richColors />
        <Footer />
      </body>
    </html>
  );
}
